name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - uses: actions/cache@v3
      with:
        node-version: 14
        cache: npm
        cache-dependency-path: angular/package-lock.json

    - name: npm install
      run: npm install
    - name: Build
      run: |
        touch src/environments/jwt.js
        npm run build
